services:
  backend:
    build: ./backend
    container_name: football-backend
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: football-frontend
    expose:
      - "80"
    depends_on:
      - backend

  nginx:
    build: ./nginx
    container_name: football-nginx
    ports:
      - "5173:80"
    depends_on:
      - frontend
      - backend